name: Mac Release App

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies and pyinstall
      run: |
        python -m pip install pip==23.0.1 setuptools==67.6.0
        pip install -r requirements.txt
        pip install PyInstaller==5.9.0
    - name: Build binary
      run: |
        python setup.py -V        
        pyinstaller --onedir -p src -n NanoVNASaver nanovna-saver.py --window --clean  -y -i icon_48x48.icns
        tar -C dist -zcf ./dist/NanoVNASaver.app-${RUNNER_ARCH}.tar.gz  NanoVNASaver.app

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NanoVNASaver-${{ vars.RUNNER_ARCH }}.tar.gz
        path: dist/NanoVNASaver.app-${{ vars.RUNNER_ARCH }}.tar.gz
